# Quarkus configuration file
# Configure the application to use the default HTTP port
quarkus.http.port=8081
quarkus.http.cors=true

# PostgreSQL database configuration (Dev)
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=P@ssw0rd
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_kafka_postgresql_dev
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.sql-load-script=import.sql

# PostgreSQL database configuration (Test)
%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.datasource.username=postgres
%test.quarkus.datasource.password=P@ssw0rd
%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_kafka_postgresql_test
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.log.sql=true
%test.quarkus.hibernate-orm.sql-load-script=import.sql

# JWT configuration
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=http://localhost:8081/realms/quarkus
mp.jwt.verify.token.age=48
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated
smallrye.jwt.sign.key.location=privateKey.pem


# Kafka configuration
kafka.bootstrap.servers=localhost:9092

# Channel for sending Security Event Monitoring
mp.messaging.outgoing.security-events-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.security-events-outgoing.topic=security-events
mp.messaging.outgoing.security-events-outgoing.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Channel for receiving Security Event Monitoring
mp.messaging.incoming.security-events-incoming.connector=smallrye-kafka
mp.messaging.incoming.security-events-incoming.topic=security-events
mp.messaging.incoming.security-events-incoming.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
